### PR TITLE
Admin interface ui

### PR DESCRIPTION
**Pull request by ericavonb**

### CODE REVIEW

**Comment by ericavonb** [comment]
@kshen0 should I just merge this?

**Comment by kshen0** [comment]
@ericavonb at this point, sure, though this seems like a prime use case for a redux rewrite!

**Comment by ericavonb** [comment]
Have at it! I'd just like to get this off my PR list :grin:

**Comment by azylman** [comment]
@ericavonb master has changed dramatically since this was written - there's a whole new backend and a frontend already exists for it. This frontend won't work since the API has changed, I'm going to revert it

**Comment by azylman** [comment]
ah, didn't notice that this was merged into not-master, so it didn't matter

**Pull request merged**
